((nil . ((cmake-ide-project-dir . "~/repos/sample-hive")
         (cmake-ide-build-dir . "~/repos/sample-hive/build")
         (cmake-ide-cmake-opts . "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPORTABLE=1 -DCMAKE_CXX_COMPILER='/usr/bin/g++'")
         (projectile-project-name . "SampleHive")
         (projectile-project-run-cmd . "~/repos/sample-hive/build/SampleHive")
         (projectile-project-test-cmd . "./test.sh"))))
